source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'C2Call-SDK_Example', :exclusive => true do
  pod "SocialCommunication", :path => "../"
end

target 'C2Call-SDK_Tests', :exclusive => true do
  pod "SocialCommunication", :path => "../"

  
end
