cp -r "../SocialCommunication/SCStoryboard.storyboard" "Pod/Assets/SCStoryboard.storyboard"
rm -rf Pod/Assets/C2CallDataModel.xcdatamodeld
cp -r "../c2callcore/C2CallDataModel.xcdatamodeld" "Pod/Assets/C2CallDataModel.xcdatamodeld"
rm -rf Pod/Assets/SocialCommunication.xcassets
cp -r "../SocialCommunication/SocialCommunication.xcassets" "Pod/Assets"
cp "../BusyTone.wav" "Pod/Assets/BusyTone.wav"
cp "../callme.wav" "Pod/Assets/callme.wav"
cp "../Dtmf-0.wav" "Pod/Assets/Dtmf-0.wav"
cp "../Dtmf-1.wav" "Pod/Assets/Dtmf-1.wav"
cp "../Dtmf-2.wav" "Pod/Assets/Dtmf-2.wav"
cp "../Dtmf-3.wav" "Pod/Assets/Dtmf-3.wav"
cp "../Dtmf-4.wav" "Pod/Assets/Dtmf-4.wav"
cp "../Dtmf-5.wav" "Pod/Assets/Dtmf-5.wav"
cp "../Dtmf-6.wav" "Pod/Assets/Dtmf-6.wav"
cp "../Dtmf-7.wav" "Pod/Assets/Dtmf-7.wav"
cp "../Dtmf-8.wav" "Pod/Assets/Dtmf-8.wav"
cp "../Dtmf-9.wav" "Pod/Assets/Dtmf-9.wav"
cp "../Dtmf-hash.wav" "Pod/Assets/Dtmf-hash.wav"
cp "../Dtmf-star.wav" "Pod/Assets/Dtmf-star.wav"
cp "../error.wav" "Pod/Assets/error.wav"
cp "../get_msg.wav" "Pod/Assets/get_msg.wav"
cp "../holdtheline.wav" "Pod/Assets/holdtheline.wav"
cp "../Message Tone.aiff" "Pod/Assets/Message Tone.aiff"
cp "../Message Tone.wav" "Pod/Assets/Message Tone.wav"
cp "../message.wav" "Pod/Assets/message.wav"
cp "../messagebeep.wav" "Pod/Assets/messagebeep.wav"
cp "../offerwall.wav" "Pod/Assets/offerwall.wav"
cp "../ringout.wav" "Pod/Assets/ringout.wav"
cp "../ringtone-bg.aif" "Pod/Assets/ringtone-bg.aif"
cp "../ringtone.wav" "Pod/Assets/ringtone.wav"
cp "../send_msg.wav" "Pod/Assets/send_msg.wav"
cp "../Classes/AarkiBannerView.h" "Pod/Classes/AarkiBannerView.h"
cp "../Classes/AdListProtocol.h" "Pod/Classes/AdListProtocol.h"
cp "../Classes/AdWhirlHandler.h" "Pod/Classes/AdWhirlHandler.h"
cp "../Classes/AlertUtil.h" "Pod/Classes/AlertUtil.h"
cp "../Classes/AudioCellIn.h" "Pod/Classes/AudioCellIn.h"
cp "../Classes/AudioCellInStream.h" "Pod/Classes/AudioCellInStream.h"
cp "../Classes/AudioCellOut.h" "Pod/Classes/AudioCellOut.h"
cp "../Classes/AudioCellOutStream.h" "Pod/Classes/AudioCellOutStream.h"
cp "../Classes/C2ActionButton.h" "Pod/Classes/C2ActionButton.h"
cp "../Classes/C2BarButtonItem.h" "Pod/Classes/C2BarButtonItem.h"
cp "../Classes/C2BlockAction.h" "Pod/Classes/C2BlockAction.h"
cp "../SocialCommunication/C2CallAppDelegate.h" "Pod/Classes/C2CallAppDelegate.h"
cp "../Classes/C2CallConstants.h" "Pod/Classes/C2CallConstants.h"
#cp "../Classes/C2CallHandler.h" "Pod/Classes/C2CallHandler.h"
cp "../c2callcore/C2CallPhone.h" "Pod/Classes/C2CallPhone.h"
cp "../FriendCallerHD/C2ExpandViewController.h" "Pod/Classes/C2ExpandViewController.h"
cp "../Classes/C2TapImageView.h" "Pod/Classes/C2TapImageView.h"
cp "../SocialCommunication/C2WaitMessage.h" "Pod/Classes/C2WaitMessage.h"
cp "../Classes/CallCellIn.h" "Pod/Classes/CallCellIn.h"
cp "../Classes/CallCellInStream.h" "Pod/Classes/CallCellInStream.h"
cp "../Classes/CallCellOut.h" "Pod/Classes/CallCellOut.h"
cp "../Classes/CallCellOutStream.h" "Pod/Classes/CallCellOutStream.h"
cp "../Classes/ContactCellIn.h" "Pod/Classes/ContactCellIn.h"
cp "../Classes/ContactCellInStream.h" "Pod/Classes/ContactCellInStream.h"
cp "../Classes/ContactCellOut.h" "Pod/Classes/ContactCellOut.h"
cp "../Classes/ContactCellOutStream.h" "Pod/Classes/ContactCellOutStream.h"
cp "../Classes/CustomEventsBannerView.h" "Pod/Classes/CustomEventsBannerView.h"
cp "../Classes/DateUtil.h" "Pod/Classes/DateUtil.h"
cp "../Classes/DDXML.h" "Pod/Classes/DDXML.h"
cp "../Classes/DDXMLDocument.h" "Pod/Classes/DDXMLDocument.h"
cp "../Classes/DDXMLElement.h" "Pod/Classes/DDXMLElement.h"
cp "../Classes/Additions/DDXMLElementAdditions.h" "Pod/Classes/DDXMLElementAdditions.h"
#cp "../Classes/Additions/DDXMLElementAdditions.m" "Pod/Classes/DDXMLElementAdditions.m"
cp "../Classes/DDXMLNode.h" "Pod/Classes/DDXMLNode.h"
mkdir -p Pod/Classes/Categories
cp "../Classes/Categories/NSString+DDXML.h" "Pod/Classes/Categories/NSString+DDXML.h"
cp "../Classes/Categories/NSString+DDXML.m" "Pod/Classes/Categories/NSString+DDXML.m"
cp "../c2callcore/NSData+AES128.h" "Pod/Classes/Categories/"
cp "../c2callcore/NSData+AES128.m" "Pod/Classes/Categories/"
cp "../c2callcore/Crypto.h" "Pod/Classes"
cp "../Classes/debug.h" "Pod/Classes/debug.h"
cp "../Classes/EAGLView.h" "Pod/Classes/EAGLView.h"
cp "../Classes/EAGLViewController.h" "Pod/Classes/EAGLViewController.h"
cp "../Classes/EditCell.h" "Pod/Classes/EditCell.h"
cp "../Classes/FCLocation.h" "Pod/Classes/FCLocation.h"
cp "../Classes/FileCellIn.h" "Pod/Classes/FileCellIn.h"
cp "../Classes/FileCellInStream.h" "Pod/Classes/FileCellInStream.h"
cp "../Classes/FileCellOut.h" "Pod/Classes/FileCellOut.h"
cp "../Classes/FileCellOutStream.h" "Pod/Classes/FileCellOutStream.h"
cp "../Classes/FlurryAdList.h" "Pod/Classes/FlurryAdList.h"
cp "../Classes/FlurryAppCircleBannerView.h" "Pod/Classes/FlurryAppCircleBannerView.h"
cp "../Classes/FlurryClipsBannerView.h" "Pod/Classes/FlurryClipsBannerView.h"
cp "../Classes/FlurryDownloadBannerView.h" "Pod/Classes/FlurryDownloadBannerView.h"
cp "../C2Call VoIP/FlurryEventProtocol.h" "Pod/Classes/FlurryEventProtocol.h"
cp "../Classes/FlurryReengageBannerView.h" "Pod/Classes/FlurryReengageBannerView.h"
cp "../Classes/FriendCellIn.h" "Pod/Classes/FriendCellIn.h"
cp "../Classes/FriendCellInStream.h" "Pod/Classes/FriendCellInStream.h"
cp "../Classes/FriendCellOut.h" "Pod/Classes/FriendCellOut.h"
cp "../Classes/FriendCellOutStream.h" "Pod/Classes/FriendCellOutStream.h"
cp "../Classes/ImageCellIn.h" "Pod/Classes/ImageCellIn.h"
cp "../Classes/ImageCellInStream.h" "Pod/Classes/ImageCellInStream.h"
cp "../Classes/ImageCellOut.h" "Pod/Classes/ImageCellOut.h"
cp "../Classes/ImageCellOutStream.h" "Pod/Classes/ImageCellOutStream.h"
cp "../c2callcore/ImageUtil.h" "Pod/Classes/ImageUtil.h"
cp "../Classes/IOS.h" "Pod/Classes/IOS.h"
cp "../Classes/LocationCellIn.h" "Pod/Classes/LocationCellIn.h"
cp "../Classes/LocationCellInStream.h" "Pod/Classes/LocationCellInStream.h"
cp "../Classes/LocationCellOut.h" "Pod/Classes/LocationCellOut.h"
cp "../Classes/LocationCellOutStream.h" "Pod/Classes/LocationCellOutStream.h"
cp "../Classes/MdotMAdList.h" "Pod/Classes/MdotMAdList.h"
cp "../Classes/MessageCell.h" "Pod/Classes/MessageCell.h"
cp "../Classes/MessageCellIn.h" "Pod/Classes/MessageCellIn.h"
cp "../Classes/MessageCellInStream.h" "Pod/Classes/MessageCellInStream.h"
cp "../Classes/MessageCellOut.h" "Pod/Classes/MessageCellOut.h"
cp "../Classes/MessageCellOutStream.h" "Pod/Classes/MessageCellOutStream.h"
cp "../c2callcore/MOAddress.h" "Pod/Classes/MOAddress.h"
cp "../c2callcore/MOC2CallEvent.h" "Pod/Classes/MOC2CallEvent.h"
cp "../c2callcore/MOC2CallGroup.h" "Pod/Classes/MOC2CallGroup.h"
cp "../c2callcore/MOC2CallUser.h" "Pod/Classes/MOC2CallUser.h"
cp "../c2callcore/MOC2CallUser.m" "Pod/Classes"
cp "../c2callcore/MOC2CallUser+CoreDataProperties.h" "Pod/Classes"
cp "../c2callcore/MOC2CallUser+CoreDataProperties.m" "Pod/Classes"
cp "../c2callcore/MOCallHistory.h" "Pod/Classes"
cp "../c2callcore/MOCallHistory.m" "Pod/Classes"
cp "../c2callcore/MOCallHistory+CoreDataProperties.h" "Pod/Classes"
cp "../c2callcore/MOCallHistory+CoreDataProperties.m" "Pod/Classes"
cp "../c2callcore/MOChatHistory.h" "Pod/Classes"
cp "../c2callcore/MOChatHistory.m" "Pod/Classes"
cp "../c2callcore/MOChatHistory+CoreDataProperties.h" "Pod/Classes"
cp "../c2callcore/MOChatHistory+CoreDataProperties.m" "Pod/Classes"
cp "../c2callcore/MODidNumber.h" "Pod/Classes/MODidNumber.h"
cp "../c2callcore/MOGroupMember.h" "Pod/Classes/MOGroupMember.h"
cp "../c2callcore/MOGroupMember.m" "Pod/Classes"
cp "../c2callcore/MOGroupMember+CoreDataProperties.h" "Pod/Classes"
cp "../c2callcore/MOGroupMember+CoreDataProperties.m" "Pod/Classes"
cp "../c2callcore/MOTimelineEvent.h" "Pod/Classes"
cp "../c2callcore/MOTimelineEvent.m" "Pod/Classes"
cp "../c2callcore/MOTimelineEvent+CoreDataProperties.h" "Pod/Classes"
cp "../c2callcore/MOTimelineEvent+CoreDataProperties.m" "Pod/Classes"
cp "../c2callcore/MOC2CallBroadcast.h" "Pod/Classes"
cp "../c2callcore/MOC2CallBroadcast.m" "Pod/Classes"
cp "../c2callcore/MOC2CallBroadcast+CoreDataProperties.h" "Pod/Classes"
cp "../c2callcore/MOC2CallBroadcast+CoreDataProperties.m" "Pod/Classes"
cp "../c2callcore/MOOpenId.h" "Pod/Classes/MOOpenId.h"
cp "../c2callcore/MOPhoneNumber.h" "Pod/Classes/MOPhoneNumber.h"
cp "../c2callcore/MOUserData.h" "Pod/Classes/MOUserData.h"
cp "../c2callcore/MOUserData.m" "Pod/Classes"
cp "../c2callcore/MOUserData+CoreDataProperties.h" "Pod/Classes"
cp "../c2callcore/MOUserData+CoreDataProperties.m" "Pod/Classes"
cp "../Classes/R1AdList.h" "Pod/Classes/R1AdList.h"
cp "../Classes/RadiumOneBannerView.h" "Pod/Classes/RadiumOneBannerView.h"
cp "../Classes/RingtoneHandler.h" "Pod/Classes/RingtoneHandler.h"
cp "../Classes/RTPVideoHandler.h" "Pod/Classes/RTPVideoHandler.h"
cp "../SocialCommunication/SCAbstractRegistrationController.h" "Pod/Classes/SCAbstractRegistrationController.h"
cp "../SocialCommunication/SCAddGroupController.h" "Pod/Classes/SCAddGroupController.h"
cp "../SocialCommunication/SCAddressBookCell.h" "Pod/Classes/SCAddressBookCell.h"
cp "../SocialCommunication/SCAddressBookController.h" "Pod/Classes/SCAddressBookController.h"
cp "../SocialCommunication/SCAdListCell.h" "Pod/Classes/SCAdListCell.h"
cp "../SocialCommunication/SCAdTableViewController.h" "Pod/Classes/SCAdTableViewController.h"
cp "../SocialCommunication/SCAdViewContainer.h" "Pod/Classes/SCAdViewContainer.h"
cp "../SocialCommunication/SCAffiliateInfo.h" "Pod/Classes/SCAffiliateInfo.h"
cp "../SocialCommunication/SCAudioPlayerController.h" "Pod/Classes/SCAudioPlayerController.h"
cp "../SocialCommunication/SCAudioRecorderController.h" "Pod/Classes/SCAudioRecorderController.h"
cp "../SocialCommunication/SCBoardController.h" "Pod/Classes/SCBoardController.h"
cp "../SocialCommunication/SCBoardController.m" "Pod/Classes/SCBoardController.m"
cp "../SocialCommunication/SCBroadcastController.h" "Pod/Classes/SCBroadcastController.h"
cp "../SocialCommunication/SCBroadcastController.m" "Pod/Classes/SCBroadcastController.m"
cp "../SocialCommunication/SCMyBroadcastsController.h" "Pod/Classes"
cp "../SocialCommunication/SCMyBroadcastsController.m" "Pod/Classes"
cp "../SocialCommunication/SCBroadcastPlaybackController.h" "Pod/Classes"
cp "../SocialCommunication/SCBroadcastPlaybackController.m" "Pod/Classes"
cp "../SocialCommunication/SCBroadcastsAroundMeController.h" "Pod/Classes"
cp "../SocialCommunication/SCBroadcastsAroundMeController.m" "Pod/Classes"
cp "../SocialCommunication/SCBroadcastChatController.h" "Pod/Classes/SCBroadcastChatController.h"
cp "../SocialCommunication/SCBroadcastChatController.m" "Pod/Classes/SCBroadcastChatController.m"
cp "../SocialCommunication/SCBroadcastInfoController.h" "Pod/Classes/SCBroadcastInfoController.h"
cp "../SocialCommunication/SCBroadcastInfoController.m" "Pod/Classes/SCBroadcastInfoController.m"
cp "../SocialCommunication/SCBroadcastStatusController.h" "Pod/Classes/SCBroadcastStatusController.h"
cp "../SocialCommunication/SCBroadcastStatusController.m" "Pod/Classes/SCBroadcastStatusController.m"
cp "../SocialCommunication/SCBroadcastStartController.h" "Pod/Classes/SCBroadcastStartController.h"
cp "../SocialCommunication/SCBroadcastStartController.m" "Pod/Classes/SCBroadcastStartController.m"
cp "../SocialCommunication/SCBroadcastRecordingController.h" "Pod/Classes/SCBroadcastRecordingController.h"
cp "../SocialCommunication/SCBroadcastRecordingController.m" "Pod/Classes/SCBroadcastRecordingController.m"
cp "../SocialCommunication/SCBroadcastVideoController.h" "Pod/Classes/SCBroadcastVideoController.h"

cp "../SocialCommunication/SCTimeline.h" "Pod/Classes"
cp "../SocialCommunication/SCTimelineController.h" "Pod/Classes"
cp "../SocialCommunication/SCTimelineController.m" "Pod/Classes"
cp "../SocialCommunication/SCTimelineMasterController.h" "Pod/Classes"
cp "../SocialCommunication/SCTimelineMasterController.m" "Pod/Classes"

cp "../SocialCommunication/SCAudioRecordingOverlayController.h" "Pod/Classes"
cp "../SocialCommunication/SCAudioRecordingOverlayController.m" "Pod/Classes"

cp "../SocialCommunication/SCPTTPlayer.h" "Pod/Classes"
cp "../SocialCommunication/SCPTTRecorder.h" "Pod/Classes"

cp "../SocialCommunication/SCBrowserViewController.h" "Pod/Classes/SCBrowserViewController.h"
cp "../SocialCommunication/SCBubbleViewIn.h" "Pod/Classes/SCBubbleViewIn.h"
cp "../SocialCommunication/SCBubbleViewOut.h" "Pod/Classes/SCBubbleViewOut.h"
cp "../SocialCommunication/SCCallStatusController.h" "Pod/Classes/SCCallStatusController.h"
cp "../SocialCommunication/SCChatController.h" "Pod/Classes/SCChatController.h"
cp "../SocialCommunication/SCChatController.m" "Pod/Classes/SCChatController.m"
cp "../SocialCommunication/SCComposeMessageController.h" "Pod/Classes/SCComposeMessageController.h"
cp "../SocialCommunication/SCComposeMessageController.m" "Pod/Classes/SCComposeMessageController.m"
cp "../SocialCommunication/SCContactDetailController.h" "Pod/Classes/SCContactDetailController.h"
cp "../SocialCommunication/SCCountrySelectionController.h" "Pod/Classes/SCCountrySelectionController.h"
cp "../SocialCommunication/SCDataManager.h" "Pod/Classes/SCDataManager.h"
cp "../SocialCommunication/SCDataTableViewController.h" "Pod/Classes/SCDataTableViewController.h"
cp "../SocialCommunication/SCDataTableViewController.m" "Pod/Classes/SCDataTableViewController.m"
cp "../SocialCommunication/SCDialButton.h" "Pod/Classes/SCDialButton.h"
cp "../SocialCommunication/SCDialPadController.h" "Pod/Classes/SCDialPadController.h"
cp "../SocialCommunication/SCDIDManager.h" "Pod/Classes/SCDIDManager.h"
cp "../SocialCommunication/SCEditStatusController.h" "Pod/Classes/SCEditStatusController.h"
cp "../SocialCommunication/SCEditStatusController.m" "Pod/Classes/SCEditStatusController.m"
cp "../SocialCommunication/SCFindFriendController.h" "Pod/Classes/SCFindFriendController.h"
cp "../SocialCommunication/SCFlexibleToolbarView.h" "Pod/Classes/SCFlexibleToolbarView.h"
cp "../SocialCommunication/SCFriendDetailController.h" "Pod/Classes/SCFriendDetailController.h"
cp "../SocialCommunication/SCFriendDetailController.m" "Pod/Classes/SCFriendDetailController.m"
cp "../SocialCommunication/SCFriendList.h" "Pod/Classes/SCFriendList.h"
cp "../SocialCommunication/SCFriendListCell.h" "Pod/Classes/SCFriendListCell.h"
cp "../SocialCommunication/SCFriendListController.h" "Pod/Classes/SCFriendListController.h"
cp "../SocialCommunication/SCFriendListController.m" "Pod/Classes/SCFriendListController.m"
cp "../SocialCommunication/SCGroup.h" "Pod/Classes/SCGroup.h"
cp "../SocialCommunication/SCFlatButton.h" "Pod/Classes"
cp "../SocialCommunication/SCBroadcast.h" "Pod/Classes"
cp "../SocialCommunication/SCGroupAddMembersCell.h" "Pod/Classes/SCGroupAddMembersCell.h"
cp "../SocialCommunication/SCGroupDetailController.h" "Pod/Classes/SCGroupDetailController.h"
cp "../SocialCommunication/SCGroupDetailController.m" "Pod/Classes/SCGroupDetailController.m"
cp "../SocialCommunication/SCGroupDetailHeaderController.h" "Pod/Classes/SCGroupDetailHeaderController.h"
cp "../SocialCommunication/SCGroupDetailHeaderController.m" "Pod/Classes/SCGroupDetailHeaderController.m"
cp "../SocialCommunication/SCGroupMemberCell.h" "Pod/Classes/SCGroupMemberCell.h"
cp "../SocialCommunication/SCGroupNameCell.h" "Pod/Classes/SCGroupNameCell.h"
cp "../SocialCommunication/SCGroupVideoCallController.h" "Pod/Classes/SCGroupVideoCallController.h"
cp "../SocialCommunication/SCHangoutBubbleViewIn.h" "Pod/Classes/SCHangoutBubbleViewIn.h"
cp "../SocialCommunication/SCHangoutBubbleViewOut.h" "Pod/Classes/SCHangoutBubbleViewOut.h"
cp "../SocialCommunication/SCHorizontalLineView.h" "Pod/Classes/SCHorizontalLineView.h"
cp "../SocialCommunication/SCInboundCallController.h" "Pod/Classes/SCInboundCallController.h"
cp "../SocialCommunication/SCKeypadController.h" "Pod/Classes/SCKeypadController.h"
cp "../SocialCommunication/SCLaunchScreenController.h" "Pod/Classes/SCLaunchScreenController.h"
cp "../SocialCommunication/SCLaunchScreenController.m" "Pod/Classes/SCLaunchScreenController.m"
cp "../SocialCommunication/SCLocationSubmitController.h" "Pod/Classes/SCLocationSubmitController.h"
cp "../SocialCommunication/SCLocationViewerController.h" "Pod/Classes/SCLocationViewerController.h"
cp "../SocialCommunication/SCLoginController.h" "Pod/Classes/SCLoginController.h"
cp "../SocialCommunication/SCLoginController.m" "Pod/Classes/SCLoginController.m"
cp "../SocialCommunication/SCMediaManager.h" "Pod/Classes/SCMediaManager.h"
cp "../SocialCommunication/SCNumberPINController.h" "Pod/Classes/SCNumberPINController.h"
cp "../SocialCommunication/SCOfferwallController.h" "Pod/Classes/SCOfferwallController.h"
cp "../SocialCommunication/SCPasswordMailController.h" "Pod/Classes/SCPasswordMailController.h"
cp "../SocialCommunication/SCPersonController.h" "Pod/Classes/SCPersonController.h"
cp "../SocialCommunication/SCPhotoViewerController.h" "Pod/Classes/SCPhotoViewerController.h"
cp "../SocialCommunication/SCPopupMenu.h" "Pod/Classes/SCPopupMenu.h"
cp "../SocialCommunication/SCPopupTableController.h" "Pod/Classes/SCPopupTableController.h"
cp "../SocialCommunication/SCPreventAPIWarnings.h" "Pod/Classes/SCPreventAPIWarnings.h"
cp "../SocialCommunication/SCPromptController.h" "Pod/Classes/SCPromptController.h"
cp "../SocialCommunication/SCPromptController.m" "Pod/Classes/SCPromptController.m"
cp "../SocialCommunication/SCPurchaseController.h" "Pod/Classes/SCPurchaseController.h"
cp "../SocialCommunication/SCPurchaseController.m" "Pod/Classes/SCPurchaseController.m"
cp "../SocialCommunication/SCPushHandler.h" "Pod/Classes/SCPushHandler.h"
cp "../SocialCommunication/SCQRCertExportController.h" "Pod/Classes/SCQRCertExportController.h"
cp "../SocialCommunication/SCQRCertImportController.h" "Pod/Classes/SCQRCertImportController.h"
cp "../Classes/ScreenControls.h" "Pod/Classes/ScreenControls.h"
cp "../SocialCommunication/SCRegistrationController.h" "Pod/Classes/SCRegistrationController.h"
cp "../SocialCommunication/SCRegistrationController.m" "Pod/Classes/SCRegistrationController.m"
cp "../SocialCommunication/SCStoreObserver.h" "Pod/Classes/SCStoreObserver.h"
cp "../SocialCommunication/SCTextField.h" "Pod/Classes/SCTextField.h"
cp "../SocialCommunication/SCUserImageController.h" "Pod/Classes/SCUserImageController.h"
cp "../SocialCommunication/SCUserProfile.h" "Pod/Classes/SCUserProfile.h"
cp "../SocialCommunication/SCUserProfileController.h" "Pod/Classes/SCUserProfileController.h"
cp "../SocialCommunication/SCUserProfileController.m" "Pod/Classes/SCUserProfileController.m"
cp "../SocialCommunication/SCUserSelectionController.h" "Pod/Classes/SCUserSelectionController.h"
cp "../SocialCommunication/SCUserStatusController.h" "Pod/Classes/SCUserStatusController.h"
cp "../SocialCommunication/SCUserStatusController.m" "Pod/Classes/SCUserStatusController.m"
cp "../SocialCommunication/SCVerifyNumberController.h" "Pod/Classes/SCVerifyNumberController.h"
cp "../SocialCommunication/SCVideoCallController.h" "Pod/Classes/SCVideoCallController.h"
cp "../SocialCommunication/SCVideoPlayerController.h" "Pod/Classes/SCVideoPlayerController.h"
cp "../SocialCommunication/SCVideoPlayerView.h" "Pod/Classes"
cp "../SocialCommunication/SCVLCVideoPlayerView.h" "Pod/Classes"
cp "../SocialCommunication/SCWaitIndicatorController.h" "Pod/Classes/SCWaitIndicatorController.h"
cp "../SocialCommunication/SCWaitIndicatorController.m" "Pod/Classes/SCWaitIndicatorController.m"
cp "../SocialCommunication/SCAssetManager.h" "Pod/Classes/SCAssetManager.h"
cp "../Classes/SearchTableController.h" "Pod/Classes/SearchTableController.h"
cp "../Classes/SIPConstants.h" "Pod/Classes/SIPConstants.h"
cp "../Classes/SIPPhone.h" "Pod/Classes/SIPPhone.h"
cp "../Classes/SIPPhoneConstants.h" "Pod/Classes/SIPPhoneConstants.h"
cp "../Classes/SIPUtil.h" "Pod/Classes/SIPUtil.h"
cp "../SocialCommunication/SocialCommunication.h" "Pod/Classes/SocialCommunication.h"
cp "../Classes/SponsorPayAdList.h" "Pod/Classes/SponsorPayAdList.h"
cp "../Classes/SponsorPayBannerView.h" "Pod/Classes/SponsorPayBannerView.h"
cp "../Classes/TrialpayAdList.h" "Pod/Classes/TrialpayAdList.h"
cp "../Classes/TrialpayBannerView.h" "Pod/Classes/TrialpayBannerView.h"
cp "../Classes/UDConnectionCell.h" "Pod/Classes/UDConnectionCell.h"
cp "../Classes/UDPhoneCell.h" "Pod/Classes/UDPhoneCell.h"
cp "../Classes/UDUserInfoCell.h" "Pod/Classes/UDUserInfoCell.h"
cp "../SocialCommunication/UIViewController+AdSpace.h" "Pod/Classes/UIViewController+AdSpace.h"
cp "../SocialCommunication/UIViewController+SCCustomViewController.h" "Pod/Classes/UIViewController+SCCustomViewController.h"
cp "../C2Call VoIP/UserInfoProtocol.h" "Pod/Classes/UserInfoProtocol.h"
cp "../Classes/VideoCellIn.h" "Pod/Classes/VideoCellIn.h"
cp "../Classes/VideoCellInStream.h" "Pod/Classes/VideoCellInStream.h"
cp "../Classes/VideoCellOut.h" "Pod/Classes/VideoCellOut.h"
cp "../Classes/VideoCellOutStream.h" "Pod/Classes/VideoCellOutStream.h"
cp "../Classes/VideoFrame.h" "Pod/Classes/VideoFrame.h"
cp "../Classes/VideoHandler.h" "Pod/Classes/VideoHandler.h"
cp "../Classes/W3IAdList.h" "Pod/Classes/W3IAdList.h"
cp "../C2Call VoIP/WaitIndicatorProtocol.h" "Pod/Classes/WaitIndicatorProtocol.h"
cp "../c2callcore/NSBundle+SDKBundle.h" Pod/Classes
cp "../c2callcore/NSBundle+SDKBundle.m" Pod/Classes
cp ../US-AreaCodes.xml Pod/Assets
cp ../area_codes.xml Pod/Assets
cp ../country_code.xml Pod/Assets
cp ../np-1.xml Pod/Assets
cp ../np-20.xml Pod/Assets
cp ../np-211.xml Pod/Assets
cp ../np-212.xml Pod/Assets
cp ../np-213.xml Pod/Assets
cp ../np-216.xml Pod/Assets
cp ../np-218.xml Pod/Assets
cp ../np-220.xml Pod/Assets
cp ../np-221.xml Pod/Assets
cp ../np-222.xml Pod/Assets
cp ../np-223.xml Pod/Assets
cp ../np-224.xml Pod/Assets
cp ../np-225.xml Pod/Assets
cp ../np-226.xml Pod/Assets
cp ../np-227.xml Pod/Assets
cp ../np-228.xml Pod/Assets
cp ../np-229.xml Pod/Assets
cp ../np-230.xml Pod/Assets
cp ../np-231.xml Pod/Assets
cp ../np-232.xml Pod/Assets
cp ../np-233.xml Pod/Assets
cp ../np-234.xml Pod/Assets
cp ../np-235.xml Pod/Assets
cp ../np-236.xml Pod/Assets
cp ../np-237.xml Pod/Assets
cp ../np-238.xml Pod/Assets
cp ../np-239.xml Pod/Assets
cp ../np-240.xml Pod/Assets
cp ../np-241.xml Pod/Assets
cp ../np-242.xml Pod/Assets
cp ../np-243.xml Pod/Assets
cp ../np-244.xml Pod/Assets
cp ../np-245.xml Pod/Assets
cp ../np-246.xml Pod/Assets
cp ../np-247.xml Pod/Assets
cp ../np-248.xml Pod/Assets
cp ../np-249.xml Pod/Assets
cp ../np-250.xml Pod/Assets
cp ../np-251.xml Pod/Assets
cp ../np-252.xml Pod/Assets
cp ../np-253.xml Pod/Assets
cp ../np-254.xml Pod/Assets
cp ../np-255.xml Pod/Assets
cp ../np-256.xml Pod/Assets
cp ../np-257.xml Pod/Assets
cp ../np-258.xml Pod/Assets
cp ../np-260.xml Pod/Assets
cp ../np-261.xml Pod/Assets
cp ../np-262.xml Pod/Assets
cp ../np-263.xml Pod/Assets
cp ../np-264.xml Pod/Assets
cp ../np-265.xml Pod/Assets
cp ../np-266.xml Pod/Assets
cp ../np-267.xml Pod/Assets
cp ../np-268.xml Pod/Assets
cp ../np-269.xml Pod/Assets
cp ../np-27.xml Pod/Assets
cp ../np-290.xml Pod/Assets
cp ../np-291.xml Pod/Assets
cp ../np-297.xml Pod/Assets
cp ../np-298.xml Pod/Assets
cp ../np-299.xml Pod/Assets
cp ../np-30.xml Pod/Assets
cp ../np-31.xml Pod/Assets
cp ../np-32.xml Pod/Assets
cp ../np-33.xml Pod/Assets
cp ../np-34.xml Pod/Assets
cp ../np-350.xml Pod/Assets
cp ../np-351.xml Pod/Assets
cp ../np-352.xml Pod/Assets
cp ../np-353.xml Pod/Assets
cp ../np-354.xml Pod/Assets
cp ../np-355.xml Pod/Assets
cp ../np-356.xml Pod/Assets
cp ../np-357.xml Pod/Assets
cp ../np-358.xml Pod/Assets
cp ../np-359.xml Pod/Assets
cp ../np-36.xml Pod/Assets
cp ../np-370.xml Pod/Assets
cp ../np-371.xml Pod/Assets
cp ../np-372.xml Pod/Assets
cp ../np-373.xml Pod/Assets
cp ../np-374.xml Pod/Assets
cp ../np-375.xml Pod/Assets
cp ../np-376.xml Pod/Assets
cp ../np-377.xml Pod/Assets
cp ../np-378.xml Pod/Assets
cp ../np-379.xml Pod/Assets
cp ../np-380.xml Pod/Assets
cp ../np-381.xml Pod/Assets
cp ../np-382.xml Pod/Assets
cp ../np-385.xml Pod/Assets
cp ../np-386.xml Pod/Assets
cp ../np-387.xml Pod/Assets
cp ../np-388.xml Pod/Assets
cp ../np-389.xml Pod/Assets
cp ../np-39.xml Pod/Assets
cp ../np-40.xml Pod/Assets
cp ../np-41.xml Pod/Assets
cp ../np-420.xml Pod/Assets
cp ../np-421.xml Pod/Assets
cp ../np-423.xml Pod/Assets
cp ../np-43.xml Pod/Assets
cp ../np-44.xml Pod/Assets
cp ../np-45.xml Pod/Assets
cp ../np-46.xml Pod/Assets
cp ../np-47.xml Pod/Assets
cp ../np-48.xml Pod/Assets
cp ../np-49.xml Pod/Assets
cp ../np-500.xml Pod/Assets
cp ../np-501.xml Pod/Assets
cp ../np-502.xml Pod/Assets
cp ../np-503.xml Pod/Assets
cp ../np-504.xml Pod/Assets
cp ../np-505.xml Pod/Assets
cp ../np-506.xml Pod/Assets
cp ../np-507.xml Pod/Assets
cp ../np-508.xml Pod/Assets
cp ../np-509.xml Pod/Assets
cp ../np-51.xml Pod/Assets
cp ../np-52.xml Pod/Assets
cp ../np-53.xml Pod/Assets
cp ../np-54.xml Pod/Assets
cp ../np-55.xml Pod/Assets
cp ../np-56.xml Pod/Assets
cp ../np-57.xml Pod/Assets
cp ../np-58.xml Pod/Assets
cp ../np-590.xml Pod/Assets
cp ../np-591.xml Pod/Assets
cp ../np-592.xml Pod/Assets
cp ../np-593.xml Pod/Assets
cp ../np-594.xml Pod/Assets
cp ../np-595.xml Pod/Assets
cp ../np-596.xml Pod/Assets
cp ../np-597.xml Pod/Assets
cp ../np-598.xml Pod/Assets
cp ../np-599.xml Pod/Assets
cp ../np-60.xml Pod/Assets
cp ../np-61.xml Pod/Assets
cp ../np-62.xml Pod/Assets
cp ../np-63.xml Pod/Assets
cp ../np-64.xml Pod/Assets
cp ../np-65.xml Pod/Assets
cp ../np-66.xml Pod/Assets
cp ../np-670.xml Pod/Assets
cp ../np-672.xml Pod/Assets
cp ../np-673.xml Pod/Assets
cp ../np-674.xml Pod/Assets
cp ../np-675.xml Pod/Assets
cp ../np-676.xml Pod/Assets
cp ../np-677.xml Pod/Assets
cp ../np-678.xml Pod/Assets
cp ../np-679.xml Pod/Assets
cp ../np-680.xml Pod/Assets
cp ../np-681.xml Pod/Assets
cp ../np-682.xml Pod/Assets
cp ../np-683.xml Pod/Assets
cp ../np-685.xml Pod/Assets
cp ../np-686.xml Pod/Assets
cp ../np-687.xml Pod/Assets
cp ../np-688.xml Pod/Assets
cp ../np-689.xml Pod/Assets
cp ../np-690.xml Pod/Assets
cp ../np-691.xml Pod/Assets
cp ../np-692.xml Pod/Assets
cp ../np-699.xml Pod/Assets
cp ../np-7.xml Pod/Assets
cp ../np-800.xml Pod/Assets
cp ../np-808.xml Pod/Assets
cp ../np-81.xml Pod/Assets
cp ../np-82.xml Pod/Assets
cp ../np-84.xml Pod/Assets
cp ../np-850.xml Pod/Assets
cp ../np-852.xml Pod/Assets
cp ../np-853.xml Pod/Assets
cp ../np-855.xml Pod/Assets
cp ../np-856.xml Pod/Assets
cp ../np-86.xml Pod/Assets
cp ../np-870.xml Pod/Assets
cp ../np-878.xml Pod/Assets
cp ../np-880.xml Pod/Assets
cp ../np-881.xml Pod/Assets
cp ../np-882.xml Pod/Assets
cp ../np-883.xml Pod/Assets
cp ../np-886.xml Pod/Assets
cp ../np-888.xml Pod/Assets
cp ../np-90.xml Pod/Assets
cp ../np-91.xml Pod/Assets
cp ../np-92.xml Pod/Assets
cp ../np-93.xml Pod/Assets
cp ../np-94.xml Pod/Assets
cp ../np-95.xml Pod/Assets
cp ../np-960.xml Pod/Assets
cp ../np-961.xml Pod/Assets
cp ../np-962.xml Pod/Assets
cp ../np-963.xml Pod/Assets
cp ../np-964.xml Pod/Assets
cp ../np-965.xml Pod/Assets
cp ../np-966.xml Pod/Assets
cp ../np-967.xml Pod/Assets
cp ../np-968.xml Pod/Assets
cp ../np-970.xml Pod/Assets
cp ../np-971.xml Pod/Assets
cp ../np-972.xml Pod/Assets
cp ../np-973.xml Pod/Assets
cp ../np-974.xml Pod/Assets
cp ../np-975.xml Pod/Assets
cp ../np-976.xml Pod/Assets
cp ../np-977.xml Pod/Assets
cp ../np-979.xml Pod/Assets
cp ../np-98.xml Pod/Assets
cp ../np-991.xml Pod/Assets
cp ../np-992.xml Pod/Assets
cp ../np-993.xml Pod/Assets
cp ../np-994.xml Pod/Assets
cp ../np-995.xml Pod/Assets
cp ../np-996.xml Pod/Assets
cp ../np-998.xml Pod/Assets
cp ../Classes/myshader.fsh Pod/Assets
cp ../Classes/myshader.vsh Pod/Assets
cp ../Classes/SearchTableCell.xib Pod/Assets
cp ../Classes/GroupActiveMemberController.xib Pod/Assets
cp ../Classes/GroupActiveMemberCell.xib Pod/Assets
cp ../Classes/EAGLViewController.xib Pod/Assets
cp ../Classes/AdWhirl/internal/AdWhirlWebBrowser.xib Pod/Assets
cp ../libvpx.a Libraries/
#cp ../Classes/G729/libg729b.a Libraries/
cp ../Classes/libopus.a Libraries/
cp ../SocialCommunication/Release-Notes.txt .
#cp "Example/Pods/Target Support Files/C2Call-SDK/C2Call-SDK-umbrella.h" Pod/Classes
